daml/Main.daml, daml/Marketplace/Role.daml
An attempt at adding support for multiple issuers. This changes the onboarding flow slightly - custodians must be onboarded before issuers.
=> add multi issuer support

daml.yaml, daml/Main.daml, daml/Marketplace/Role.daml, daml/Marketplace/Trading.daml
- In this PR we attempt better handling of order qty calculation given an asset deposit qty.
- We also use the quote token's qty precision as the tick size for creating bids and offers
- bump to sdk 1.4.0
=> better handling of order qty calculation given qty precisions

daml/Main.daml, daml/Marketplace/Role.daml, daml/Marketplace/Trading.daml
with this PR we aim to decouple the onboarding of a role (Exchange, Issuer, Custodian, Investor) in the marketplace from the relationships between roles (ie custodian <> investor and custodian <> exchange).
This will make the onboarding flow of the parties independent and will allow for adding onboarding automation. The model has also been updated to include a UserSession contract that will eventually be used by automation
In this PR we also remove some of the visibility of the Operator party (especially when it comes to orders placed on an exchange)
=> better role onboarding. reduce operator visibility

Makefile, automation/operator/.gitignore, automation/operator/bot/__init__.py, automation/operator/bot/operator_bot.py, automation/operator/poetry.lock, automation/operator/pyproject.toml, daml/Main.daml, daml/Marketplace/Role.daml
- An operator bot is introduced to ack UserSession contracts and create the appropriate role invitations.
- The public party is now a field and an observer in all publicly displayed contracts.
- Once accepting a role invitation each party gets a role contract as well as a public registry contract. Investor parties are optionally not disclosed to the public party
=> Add operator bot, public party and role ref data

daml/Main.daml, daml/Marketplace/Broker.daml, daml/Marketplace/Investor.daml, daml/Marketplace/Onboarding.daml, daml/Marketplace/Trading.daml, daml/Marketplace/Transfer.daml, ui/src/components/Investor/InvestorWallet.tsx
Some model changes to support the broker flow.
- Given that we now have multiple account providers (ie @Exchange @Custodian @Broker) it makes sense to change the `AllocateToExchange` choice to a more generic `AllocateToProvider`.
=> Changes to support the entire broker flow

daml/Marketplace/Custodian.daml, daml/Marketplace/Exchange.daml, daml/Marketplace/Investor.daml, daml/Marketplace/Issuer.daml, daml/Marketplace/Onboarding.daml, daml/Marketplace/Utils.daml, ui/src/components/RoleSelectScreen.tsx
Creates a `MarketRole` type to be used for pattern matching on role types instead of on strings. Currently used in Custodian, Onboarding and RoleSelectScreen.
=> Add role sumtype

daml/Marketplace/Transfer.daml, ui/src/components/common/Holdings.tsx
this PR addresses Issue #56 .
- Filters out the asset deposit's current account provider from the allocate to exchange dropdown
- Adds DAML precondition to not create transfers where source == destination
- Adds Transfer reject custodian choice for future use with bot
=> add precondition and filter ui to prevent bad transfer requests

ui/src/components/Broker/Broker.tsx, ui/src/components/Broker/BrokerSideNav.tsx, ui/src/components/Custodian/Custodian.tsx, ui/src/components/Custodian/CustodianSideNav.tsx, ui/src/components/Exchange/Exchange.tsx, ui/src/components/Exchange/ExchangeSideNav.tsx, ui/src/components/Investor/Investor.tsx, ui/src/components/Investor/InvestorSideNav.tsx, ui/src/components/Issuer/Issuer.tsx, ui/src/components/Issuer/IssuerSideNav.tsx
Fixes the name in the sidebar flashing by passing down the name from the main page for each role.
Addresses https://github.com/digital-asset/da-marketplace/issues/79.
=> fix sidebar name flashing

ui/src/components/Custodian/Custodian.tsx, ui/src/components/Custodian/RelationshipInviteNotifications.tsx, ui/src/components/Custodian/RelationshipRequestNotifications.tsx, ui/src/components/Exchange/ExchangeParticipants.tsx, ui/src/components/common/MarketRelationships.tsx, ui/src/components/common/RegistryLookup.tsx, ui/src/components/common/RequestCustodianRelationship.tsx, ui/src/components/common/damlTypes.ts
- Adds Custodian Relationship Request Notifications to the Custodian Page
- Remove already requested custodians from the request dropdown
- Removes already invited participants from the exchange invite dropdown
- Change the formatting of market relationships
Address https://github.com/digital-asset/da-marketplace/issues/77.
=> Add relationship request notifications

daml/Main.daml, daml/Marketplace/Trading.daml, exberry_adapter/bot/exberry_adapter_bot.py, matching_engine/bot/matching_engine_bot.py, ui/src/components/Investor/InvestorOrders.tsx, ui/src/components/common/BrokerTradeCard.tsx, ui/src/components/common/TradeCard.tsx
This addresses issue #51 
- Add the concept of `TradeSide` to the daml model that evidences an exchange trade for a specific party. The trade now contains the time traded as well as the order ids that matched on the engine
- Add a `BrokerTrade` to the daml model to hold all the fill information for a trade between a broker and their customer
- Add exchange trades and broker trades for investors on UI
~Hasn't been fully tested~
Tested end-to-end on a prod ledger with the Exberry integration
=> Evidence Trades

ui/src/components/Broker/Broker.tsx, ui/src/components/Custodian/Clients.tsx, ui/src/components/Exchange/ExchangeParticipants.tsx, ui/src/components/Investor/Investor.tsx, ui/src/components/common/Holdings.css, ui/src/components/common/Holdings.tsx, ui/src/components/common/utils.ts
Closes #52, #53, #84 
- Displays amount investors have committed in the exchange view
- Pass in an array of `providers` to the Holdings component
- Groups asset deposits of the same asset together into sections, then lists each individual deposit with options beneath it 
- Splits each button into separate forms to avoid duplicate transfer requests
- You can't merge deposits if the account providers are different, so I filter those options accordingly
=> Display all providers, amounts committed

ui/src/Credentials.ts, ui/src/components/App.tsx, ui/src/components/LoginScreen.tsx
This PR fixes two issues: 
1) when refreshing the page on DABL, you used to get that 404 nginx error. Fixed by using HashRouter.
2) when refreshing the page (in general), you'd fall back to the login screen because credentials are not persisted. 
This also makes sure there's some type safety around the JSON-ified credentials that are read out of localStorage. 
In theory, once the token expires after 24h, then the app should redirect the user back to the login page as if it was never in the store at all, though this code path remains to be tested
=> Use HashRouter and persist credentials to localStorage

Makefile, automation/broker/pyproject.toml, automation/custodian/pyproject.toml, automation/exchange/pyproject.toml, automation/issuer/pyproject.toml, automation/operator/pyproject.toml, dabl-meta.yaml, daml.yaml, daml/Marketplace/Utils.daml, exberry_adapter/bot/exberry_adapter_bot.py, exberry_adapter/pyproject.toml, matching_engine/pyproject.toml, ui/package.json
Add a contract called `ExberryPID` that can be created to tell the exberry adapter what PID to use for order IDs. Also includes the exberry adapter in the distributed dit file.
=> Exberry pid contract

Makefile
`marketplace.svg` needs to be added to the `.dit` zip in the root, this adds it to the `zip` stage in the `Makefile`.
=> add marketplace.svg to make package dit zip

automation/broker/pyproject.toml, automation/custodian/pyproject.toml, automation/exchange/pyproject.toml, automation/issuer/pyproject.toml, automation/operator/pyproject.toml, dabl-meta.yaml, daml.yaml, daml/Main.daml, daml/Marketplace/Exchange.daml, daml/Marketplace/Token.daml, daml/Setup.daml, exberry_adapter/bot/exberry_adapter_bot.py, exberry_adapter/poetry.lock, exberry_adapter/pyproject.toml, matching_engine/pyproject.toml, ui/package.json, ui/src/components/Exchange/CreateMarket.css, ui/src/components/Exchange/CreateMarket.tsx
Allows Exberry integration to pick up `CreateInstrumentRequest`s when a new market is created by the exchange. Also adds minimum quantity and maximum quantity to the market.
TODO: orders in exberry will fail when the pair is outside of the minimum/maximum range, but this should also be enforced by the DAML model as well. Due to visibility of the `MarketPair` contract, this will most likely necessitate changes to the automation, so I'd prefer to wait until after the triggers are merged in.
=> Add create instrument

daml/Marketplace/Investor.daml, daml/Marketplace/Trading.daml, daml/Marketplace/Transfer.daml
Adds a withdraw/deposit choice to the investor role contract. This uses `Transfer.DepositDebitRequest` and `Transfer.DepositCreditRequest` which are automatically resolved by the custodian trigger. If we want to change it so the custodian has to manually approve each request, we may have to create separate requests in the Custodian module, as the `Trading` requests are also used by the exchange (which will most likely need to remain auto-approved).
Also fixed a few places where the issuer was being removed from the observers on asset deposits in a few places.
=> Investor deposit/withdraw and issuer observe

daml/Marketplace/ExchangeParticipant.daml, daml/Tests/ExchangeTrade.daml, ui/src/components/Custodian/CreateDeposit.tsx, ui/src/components/Exchange/CreateMarket.tsx, ui/src/components/Investor/InvestorTrade.tsx, ui/src/components/Investor/OrderForm.css, ui/src/components/Investor/OrderForm.tsx, ui/src/components/common/FormErrorHandled.tsx, ui/src/components/common/Holdings.tsx, ui/src/components/common/errorTypes.ts, ui/src/components/common/utils.ts
This starts adding some improvements to the Order Form for investors. 
The main thing is instead of selecting a deposit from a dropdown, you are free to enter any amount you wish. The UI looks up available deposits and picks the first deposit CID that contains at least that amount, and exercises the same choice as it used to. 
The choice now performs the split automatically if the amount is less than the total amount of the deposit.
I also added a read-only text input that previews the total amount of asset you'll get if the order gets accepted and filled, and some nicer error handling if the amount is invalid for some reason.
=> Order amount splits

daml/Marketplace/Claims.daml, daml/Marketplace/Custody.daml, daml/Marketplace/Issuance.daml
Move out all the `Claim` related code into a separate module. This is mainly so as not to pollute the `Issuance`  imports.
=> Factor out all fns dealing with claims into a module

ui/src/components/Broker/Broker.tsx, ui/src/components/CCP/ExchangeRelationships.tsx, ui/src/components/CCP/Members.tsx, ui/src/components/Exchange/Exchange.tsx, ui/src/components/Exchange/ExchangeParticipants.tsx, ui/src/components/Investor/Investor.tsx, ui/src/components/Issuer/Issuer.tsx, ui/src/components/common/AddRegisteredPartyModal.tsx, ui/src/components/common/MarketRelationships.tsx, ui/src/components/common/RequestCustodianRelationship.tsx, ui/src/components/common/damlTypes.ts
This makes relationship dropdowns multi-selectable (except for the Exchange's investor invite, that will need some Daml treatment) 
Also fixes the Issuer nav to display only their own issued tokens
=> Multiselect relationships + issuer nav

ui2/src/App.tsx, ui2/src/components/Table/PaginationControls.scss, ui2/src/components/Table/PaginationControls.tsx, ui2/src/components/Table/StripedTable.scss, ui2/src/components/Table/StripedTable.tsx, ui2/src/components/Tile/Tile.scss, ui2/src/components/Tile/Tile.tsx, ui2/src/index.scss, ui2/src/pages/issuance/New.tsx, ui2/src/pages/login/Login.tsx, ui2/src/pages/origination/Instruments.tsx, ui2/src/pages/page/Page.tsx
This PR starts some work of substituting Material UI components with ones more line with the rest of the styles. I decided to include some simple documentation in this PR description, hopefully you guys will find it helpful when making these substitutions elsewhere! 
Importable from `components/Table/StripedTable`, this is (one of) the component that we used in `ui` on master for displaying tables.  We should be able to convert all the existing Material UI tables to StripedTables pretty easily. The table headers and rows are passed in as props. 
See `Instruments.tsx` in origination (in this PR) for an example. 
Tile can be used for blocks of content on a page. Pretty self-explanatory, it takes in children for content but also has a `header` prop for a title. 
This is a component that we …
=> Reusable tables & Issuance

daml.yaml, daml/Common.daml, daml/Marketplace/Operator/Role.daml, daml/Marketplace/Regulator/Role.daml, triggers/daml/AutoApproval.daml, ui2/src/pages/login/QuickSetup.tsx
This adds a regulator role template, which was necessary in order to be automated in the auto-approve trigger. Now the entire flow of requesting a regulator service, acceptance, then requesting identity verification, and acceptance is covered end-to-end by the trigger. 
I had to make some changes to Quick Setup due to the new codegen, and I got to build successfully but the identity requests made through there have broken again... I will keep looking into that later today/tmrrw
=> get quick setup to build

ui2/src/Main.tsx, ui2/src/websocket/queryStream.ts, ui2/src/websocket/websocket.ts
pulls in the code from the old marketplace that pools query streams into a single websocket connection. Template names are subscribed to, and the connection is reestablished with the initial message resent to include the new template ID.
=> add pooled websocket connections

ui2/src/components/Table/StripedTable.tsx, ui2/src/pages/clearing/Members.tsx, ui2/src/pages/custody/Assets.tsx, ui2/src/pages/distribution/auction/Auctions.tsx, ui2/src/pages/distribution/bidding/Auctions.tsx, ui2/src/pages/issuance/Issuances.tsx, ui2/src/pages/origination/Instruments.tsx, ui2/src/pages/origination/Requests.tsx, ui2/src/pages/trading/Market.tsx, ui2/src/pages/trading/Order.tsx
adds a prop to `StripedTable` to show an icon
=> add icon to table button

.gitmodules
This points to the new open-source repo under the digital-asset
organisation. The hashes differ as the history was re-written,
but the commit is the same.
=> Point to new OSS claims repo

daml/Common.daml, ui/package-lock.json, ui/package.json, ui/src/index.scss, ui/src/pages/custody/Account.tsx, ui/src/pages/custody/Accounts.tsx, ui/src/pages/landing/Landing.tsx, ui/src/pages/origination/Instrument.scss, ui/src/pages/origination/Instrument.tsx, ui2/src/pages/issuance/Issuances.tsx
The one caveat is that observers are added when the deposit is made by the investor from the UI, so when bootstrapping data locally the issuer will not be an observer of the asset until the investor's wallet screen is rendered. 
In a demo setting, when manually creating the deposits this should not be an issue..
=> added position holdings view for issuer of asset

daml/Common.daml, daml/Marketplace/Clearing/Role.daml, daml/Marketplace/Custody/Role.daml, daml/Marketplace/Operator/Role.daml, daml/Marketplace/Trading/Role.daml, docs/user_guide.md, ui/src/pages/QuickSetup/AddPartiesPage.tsx, ui/src/pages/QuickSetup/QuickSetup.scss, ui/src/pages/QuickSetup/RequestServicesPage.tsx, ui/src/pages/QuickSetup/SelectRolesPage.tsx, ui/src/pages/network/Trading.tsx
Self-referential services:
- customer accepts clearing role and automatically offers itself clearing service with ccp account
- customer accepts custody role and automatically offers itself custody and issuance services
- customer accepts exchange role and automatically offers itself matching (was already there), settlement (was already there) and listing (new) services
also adjusts numbering in the user guide to make it easier to modify parts of various sections without hving to re-number the whole thing
also fixes non-readable name in service request page of quick setup
=> Self ref services

daml/Marketplace/Custody/Service.daml, daml/Marketplace/Issuance/Service.daml, daml/Marketplace/Rule/AllocationAccount.daml, ui/src/pages/QuickSetup/RequestServicesPage.tsx, ui/src/pages/custody/Account.tsx
When an asset deposit is created, the signatories of that asset are added as observers. That way any issuer can view allocations of their asset.
=> Add asset signatories to newly created asset deposits

ui/src/App.tsx, ui/src/components/Common/TitleWithActions.scss, ui/src/components/Form/ModalFormErrorHandled.tsx, ui/src/components/Tile/Tile.scss, ui/src/icons/icons.tsx, ui/src/pages/custody/Account.scss, ui/src/pages/custody/Account.tsx, ui/src/pages/custody/Assets.tsx, ui/src/pages/custody/New.tsx, ui/src/pages/page/PageSection.scss, ui/src/themes/button.scss
Instead of a Holdings table followed by an Account table, we now have holdings listed under their designated accounts and a quick deposit tile like the previous marketplace had. This kind of refactor is also working toward flattening the UX where we can i.e. reducing nested pages
=> Flatten wallet information 

daml/Marketplace/Distribution/Bidding/Service.daml, daml/Marketplace/Rule/AllocationAccount.daml, daml/Marketplace/Settlement/Model.daml, daml/Marketplace/Trading/Confirmation/Model.daml, daml/Marketplace/Trading/Model.daml, daml/Marketplace/Trading/Role.daml, daml/Marketplace/Trading/Service.daml, daml/Tests/Clearing.daml, daml/Tests/ExchangeTrade.daml, daml/Tests/Locking.daml, daml/Tests/Trading/Cleared.daml, daml/Tests/Trading/E2E.daml, daml/Tests/Trading/Fees.daml, daml/Tests/Utils.daml, exberry_adapter/bot/exberry_adapter_bot.py, triggers/daml/MatchingEngine.daml, ui/src/App.tsx, ui/src/components/Tile/Tile.tsx, ui/src/pages/listing/New.tsx, ui/src/pages/network/Fees.tsx, ui/src/pages/network/Trading.tsx, ui/src/pages/trading/Market.tsx
Adds Exchange Fees via an `Optional` `ContractId AssetDeposit` field in the order details and a customizable `FeeSchedule` contract that the Exchange can set. Orders that do not include the correct fee will be rejected by the MatchingEngine or Exchange Adapter (this is also enforced in the UI). When the order is matched and confirmed, the fees are moved into an account held by the Exchange. Fees are prorated when an order is partially filled.
=> Add exchange fees

daml/Marketplace/Clearing/Market/Model.daml, daml/Marketplace/Clearing/Market/Service.daml, triggers/daml/ClearingTrigger.daml, ui/src/App.tsx, ui/src/pages/listing/Listing.tsx, ui/src/pages/listing/Listings.tsx
- add a calculationId field to fair value and fair values requests
- allow custom `upTo` for fair value requests
- allow all parties to see listings and listing details
=> add calculationId and upTo to FairValueRequest, show listings to all parties

ui/src/components/InputDialog/Fields.tsx, ui/src/components/InputDialog/RoleDialog.tsx, ui/src/components/InputDialog/ServiceDialog.tsx, ui/src/pages/error/ServiceRequired.tsx, ui/src/pages/landing/RoleRequestMenu.tsx, ui/src/pages/landing/ServiceRequestMenu.tsx, ui/src/pages/notifications/NotificationComponents.tsx, ui/src/pages/setup/Offer.tsx
Fixes the problem reported by @brian-weir about blank dropdowns. The main problem was a simple type error, which wasn't caught by the compiler because some of the `fields` props were typed as `any` or `object`, introducing a blind-spot in the checker
=> enhanced type safety for input fields

.circleci/config.yml, daml/Marketplace/Distribution/Syndication/Structuring/Model.daml, daml/Marketplace/Distribution/Syndication/Structuring/Service.daml, daml/Marketplace/Issuance/Instrument/Model.daml, daml/Marketplace/Settlement/Hierarchical.daml, daml/SwiftMessage/Message.daml, daml/SwiftMessage/Model/MT545.daml, daml/SwiftMessage/Model/MT547.daml, daml/SwiftMessage/Util.daml, daml/Tests/Distribution/Syndication/Issuance.daml, daml/Tests/Distribution/Syndication/Origination.daml, daml/Tests/Distribution/Syndication/Util.daml
Note that @dorrit-du-da and I have discussed and decide to leave out the change in 
FL-177 Split out calcuateEffect from lifecycle part
changes covered
FL-167 ISIN with Bond Name to be added to the tranche
FL-168 Move issuance parties to the Trance level from the Deal level
FL-176 Modify Trade to capture the asset movement
FL-182 MT545 message daml integration
FL-183 MT547 message daml integration
=> Syndication 2

daml/Marketplace/Issuance/Instrument/Model.daml, daml/Marketplace/Lifecycle/Model.daml, daml/Marketplace/Lifecycle/Service.daml, daml/SwiftMessage/Model/MT564.daml, daml/SwiftMessage/Model/MT566.daml, daml/SwiftMessage/Util.daml, daml/Tests/Distribution/Syndication/Origination.daml, daml/Tests/Distribution/Syndication/Util.daml
After discussion with @dorrit-du-da we would like to make some minor changes below to better support query with filtering
Changes include in this PR:
1. add issuer into Bond so swift adaptor will be able to compose the key (operator, payingAgent, issuer) and fetch Lifecycle.Service  
2. add assetId field into MT564 and MT566 for swift adaptor to filter/group SwiftOutboundMessage
=> FL-219, FL-220: add issuer into Bond and assetId into MT564 MT566

daml/Marketplace/Snapshot/Model.daml, daml/Marketplace/Snapshot/Service.daml, daml/Tests/Distribution/Syndication/IssuerRedemption.daml, daml/Tests/Distribution/Syndication/Lifecycle.daml
This is a small change on the snapshot flow. 
As we need a way to filter the snapshot contracts when we want to do sendPrePayoutMessage, lifecycling or early redemption.
Details are in the description of https://digitalasset.atlassian.net/browse/FL-267
=> FL-267: add referenceId into snapshot flow

daml/Marketplace/Distribution/Syndication/Bidding/Model.daml, daml/Marketplace/Distribution/Syndication/Structuring/Model.daml, daml/Marketplace/Distribution/Syndication/Structuring/Service.daml, daml/Marketplace/Settlement/Hierarchical.daml, daml/Marketplace/Trading/Otc/Model.daml, daml/Marketplace/Trading/Otc/Service.daml, daml/Tests/Distribution/Syndication/Issuance.daml, daml/Tests/Distribution/Syndication/Trading.daml, daml/Tests/Distribution/Syndication/Util.daml
This adds a `SettlementMode` that can be selected by a party for OTC trade settlement, or by an investor for settlement of an issuance. Settlement btw issuer, settlement bank, and BnD bank still happens through DvP.
This doesn't cover the adjustments for Swift messages to be sent out.
=> Add support for FoP settlement

daml/Marketplace/Distribution/Syndication/Structuring/Model.daml, daml/Marketplace/Settlement/Hierarchical.daml, daml/SwiftMessage/Message.daml, daml/SwiftMessage/Model/MT544.daml, daml/SwiftMessage/Model/MT545.daml, daml/SwiftMessage/Model/MT546.daml, daml/SwiftMessage/Model/MT547.daml, daml/SwiftMessage/Util.daml, daml/Tests/Distribution/Syndication/Issuance.daml
The changes in this PR includes:
1. add FOP swift messages (MT544 and MT546)
2. refactor current DvP swift messages (MT545 and MT547) along with newly added FoP messages 
3. use bond2 in the issuance script to test FoP settlement flow
Note that this change should be merged only after https://github.com/digital-asset/da-marketplace/pull/478 is merged (to avoid conflicts)
=> Swift Message Integration with FoP

daml/Marketplace/Reporting/Service.daml, daml/SwiftMessage/Model/MT535.daml, daml/SwiftMessage/Model/MT940.daml, daml/SwiftMessage/Util.daml
This PR adds T-1 business day into ReportDetails data record as we need this piece of data in MT940 message (cash reporting) as discussed in [FL-302](https://digitalasset.atlassian.net/browse/FL-302)
=> FL-302: add prev business date in report details

daml/Tests/Distribution/Syndication/Trading.daml
This PR add FoP and Htlc testing on top of https://github.com/digital-asset/da-marketplace/pull/488 and should be only merge after aforementioned PR is merged.
=> FL-309: add test script for fop and htlc in otc trading
