ui/src/components/App.tsx, ui/src/components/Issuer/IssueAsset.tsx, ui/src/components/Issuer/Issuer.tsx, ui/src/components/LoginScreen.tsx, ui/src/components/MainScreen.tsx, ui/src/components/common/SideMenu.css, ui/src/components/common/TopMenu.css, ui/src/components/common/TopMenu.tsx, ui/src/components/common/Tuple.ts, ui/src/components/investor/Investor.tsx, ui/src/components/investor/InvestorSideNav.tsx, ui/src/components/investor/InvestorTrade.tsx, ui/src/components/investor/InvestorWallet.css, ui/src/components/investor/InvestorWallet.tsx, ui/src/components/investor/OrderForm.css, ui/src/components/investor/OrderForm.tsx
This PR includes a couple of things,
- Fixed the DABL Login flow (react-router was improperly redirecting the `/?party=party&token=jwt` route created by the auth button, and in the process moved the whole login page to live on `/` since that route wasn't being used)
- Added party & token login fields for DABL envs 
- Created some helpers for encoding/decoding DAML tuples to JS arrays
- Allowed investors to allocate deposits to any exchange they are participants of
- Allowed investors to place bid and offer requests on exchanges
=> Marketplace UI Improvements & Investor Trading View

automation/issuer/bot/issuer_bot.py, daml/Main.daml, daml/Marketplace/Issuer.daml, daml/Marketplace/Token.daml, ui/src/components/Issuer/IssueAsset.tsx, ui/src/components/Issuer/IssuedToken.tsx
Added `isPublic` to the token template which controls whether or not the issuer bot will automatically add observers to it.
=> adding an isPublic flag to tokens to control their observers

daml/Main.daml, daml/Marketplace/Issuer.daml, ui/src/components/Issuer/IssueAsset.css, ui/src/components/Issuer/IssueAsset.tsx
if private, the user can add a list of observers to their asset
=> add observers to created asset

daml/Main.daml, daml/Marketplace/Broker.daml, daml/Marketplace/BrokerCustomer.daml, daml/Marketplace/Operator.daml, daml/Marketplace/Registry.daml, daml/Marketplace/Trading.daml
This is an updated take at the broker role. We don't really have to start adding front end for this yet but it is good to have it in the model to make sure we can support it.
I have added another scenario in `Main.daml` where I demonstrate a workflow in which Alice exchanges some of her BTC with USDT through a broker
=> Broker role

Makefile, automation/broker/.gitignore, automation/broker/bot/__init__.py, automation/broker/bot/broker_bot.py, automation/broker/poetry.lock, automation/broker/pyproject.toml
This PR add a bot for the broker. The functionality at the moment is limited to accepting broker order requests and assigning an id to them
=> add broker bot

automation/issuer/bot/issuer_bot.py
update the issuer bot to respond to `RegisteredBroker`s joining the system
=> update issuer bot for broker parties

automation/custodian/bot/custodian_bot.py
Make custodian bot auto-approve a relationship request
> @alexmatson-da this is the PR regarding what we discussed on the custodian bot
=> auto approve custodian relationships from bot

Makefile
some fixes to be able to easily start and stop the local stack
=> fix bot start stop targets

daml.yaml
tested with SDK 1.5.0 will also push the changes to the script repo
=> bump to sdk 1.5.0

ui/dabl-react/package.json, ui/package.json
tested the ui flow with this. looks ok
=> bump ui dependencies to sdk 1.5.0

Makefile, matching_engine/.gitignore, matching_engine/bot/__init__.py, matching_engine/bot/matching_engine_bot.py, matching_engine/poetry.lock, matching_engine/pyproject.toml
Add a bot to perform order matching. This can run instead of the exberry adapter and will facilitate when running the stack locally.
=> Local matching engine

ui/src/components/Broker/BrokerOrders.tsx, ui/src/components/Custodian/CreateDeposit.tsx, ui/src/components/Exchange/InviteParticipant.tsx, ui/src/components/Investor/OrderForm.tsx, ui/src/components/Issuer/IssueAsset.css, ui/src/components/Issuer/IssueAsset.tsx, ui/src/components/Issuer/IssuerSideNav.tsx, ui/src/components/common/Holdings.tsx, ui/src/components/common/LandingPage.css, ui/src/components/common/LandingPage.tsx, ui/src/components/common/RequestCustodianRelationship.tsx, ui/src/components/common/SideMenu.css, ui/src/components/common/TopMenu.css, ui/src/components/common/WelcomeHeader.css, ui/src/index.css
added `clearForm()` so that it can be extendable, in case more fields are added to certain forms
=> Polishing UI and added a clearForm() function where needed

ui/src/components/common/Holdings.css, ui/src/components/common/Holdings.tsx
the next thing here is to add options for naming a split deposit etc.
=> Merge and split deposits

ui/src/components/Investor/InvestorSideNav.tsx
Addresses https://github.com/digital-asset/da-marketplace/issues/49.
=> change investor sidebar to show pairs

Makefile, dabl-meta.yaml
add a `dabl-meta.yaml` file. Create a `dit` and add a make target to publish it.
This addresses #62
=> update makefile for packaging and releasing

ui/src/components/common/Holdings.css, ui/src/components/common/Holdings.tsx, ui/src/components/common/utils.ts, ui/src/index.css
Adds quantity precision check to splitting assets
=> add quant precision

ui/src/components/Custodian/CreateDeposit.tsx, ui/src/components/common/Holdings.tsx
for https://github.com/digital-asset/da-marketplace/pull/97#issue-500103973
=> add step to quantity precision hehe

daml/Main.daml, daml/Marketplace/Custodian.daml, daml/Marketplace/Investor.daml, daml/Marketplace/Issuer.daml, daml/Marketplace/Registry.daml, daml/Setup.daml, ui/src/components/Broker/Broker.tsx, ui/src/components/Custodian/Custodian.tsx, ui/src/components/Custodian/CustodianSideNav.tsx, ui/src/components/Exchange/Exchange.tsx, ui/src/components/Investor/Investor.tsx, ui/src/components/Issuer/IssuedToken.tsx, ui/src/components/Issuer/Issuer.tsx, ui/src/components/common/MarketRelationships.tsx, ui/src/components/common/Profile.tsx
- Removes private fields from templates
- Adds DAML choice to each Registry template to allow updates
Tested on DABL, ran into some bugs that are already present in master, but the profile changes here seem to be in working order
=> Allow users to update Registry profile info

Makefile, automation/broker/pyproject.toml, automation/custodian/pyproject.toml, automation/exchange/bot/exchange_bot.py, automation/exchange/poetry.lock, automation/exchange/pyproject.toml, automation/issuer/pyproject.toml, automation/operator/pyproject.toml, dabl-meta.yaml, daml.yaml, daml/Main.daml, daml/Marketplace/BinaryOption.daml, daml/Marketplace/BrokerCustomer.daml, daml/Marketplace/Exchange.daml, daml/Marketplace/ExchangeParticipant.daml, daml/Marketplace/Issuer.daml, daml/Marketplace/Token.daml, daml/Marketplace/Trading.daml, daml/Marketplace/Utils.daml, exberry_adapter/bot/exberry_adapter_bot.py, exberry_adapter/pyproject.toml, matching_engine/pyproject.toml, ui/package.json, ui/src/components/Exchange/CreateMarket.tsx, ui/src/components/Investor/InvestorOrders.tsx, ui/src/components/common/TradeCard.tsx
> Description Pending...
> Need to test this end to end
=> Binary Option Support

daml.yaml, ui/dabl-react/package.json, ui/package.json
=> bump to sdk 1.6.0

ui/src/components/LoginScreen.tsx, ui/src/config.ts
=> Use DABL Hostname

ui/src/components/Custodian/CreateDeposit.css, ui/src/components/Custodian/CreateDeposit.tsx, ui/src/components/Exchange/CreateMarket.tsx, ui/src/components/Investor/InvestorOrders.tsx, ui/src/components/common/Holdings.tsx
change "token" to asset in create market page, add dropdown to custodian deposit page
=> add party names to custodian dropdown

ui/src/Credentials.ts, ui/src/Parties.ts, ui/src/components/LoginScreen.css, ui/src/components/LoginScreen.tsx, ui/src/components/common/FormErrorHandled.tsx, ui/src/components/common/InviteAcceptTile.tsx, ui/src/components/common/OnboardingTile.css, ui/src/components/common/OnboardingTile.tsx, ui/src/components/common/Page.css, ui/src/components/common/PageSection.css, ui/src/components/common/Profile.tsx, ui/src/components/common/WelcomeHeader.tsx, ui/src/components/common/errorTypes.ts, ui/src/components/common/utils.ts, ui/src/icons/Icons.css, ui/src/icons/Icons.tsx, ui/src/index.css
Also modifies `OnboardingTile` to support an array of `Tile` UI components, each tile being separated by a small gap. See screenshot for example
=> add login widget based on parties.json

ui/src/components/Investor/Investor.scss, ui/src/components/Investor/InvestorTrade.scss, ui/src/components/Investor/InvestorTrade.tsx, ui/src/components/Investor/OrderForm.scss, ui/src/components/Investor/OrderForm.tsx, ui/src/icons/Icons.scss, ui/src/icons/Icons.tsx, ui/src/icons/candlestick.svg, ui/src/index.scss
=> Bidirectional order form

README.md, dabl-meta.yaml, daml.yaml, exberry_adapter/pyproject.toml, triggers/daml.yaml, ui/package.json, ui/src/Parties.ts
Also bump the version for a release
=> Update parties.json parser with new DABL JWT format updates

ui/src/components/Broker/BrokerOrders.tsx, ui/src/components/Custodian/ClientHoldings.tsx, ui/src/components/Custodian/Clients.scss, ui/src/components/Custodian/Clients.tsx, ui/src/components/Custodian/CreateDeposit.scss, ui/src/components/Exchange/ExchangeParticipants.scss, ui/src/components/Issuer/IssueAsset.scss, ui/src/components/Issuer/IssuedToken.scss, ui/src/components/common/CardTable.scss, ui/src/components/common/CardTable.tsx, ui/src/components/common/Holdings.scss, ui/src/components/common/Holdings.tsx, ui/src/components/common/Page.scss, ui/src/components/common/StripedTable.scss, ui/src/components/common/StripedTable.tsx, ui/src/components/common/TopMenu.scss, ui/src/components/common/TopMenu.tsx, ui/src/components/common/WelcomeHeader.scss, ui/src/index.scss
=> all pages responsive + sticky sidebar on scroll

Makefile, daml/Marketplace/CentralCounterparty.daml, daml/Marketplace/CentralCounterpartyCustomer.daml, daml/Marketplace/Exchange.daml, daml/Marketplace/ExchangeParticipant.daml, daml/Marketplace/Token.daml, daml/Marketplace/Trading.daml, daml/Tests/ExchangeTrade.daml, exberry_adapter/bot/exberry_adapter_bot.py, triggers/daml/CCPTrigger.daml, triggers/daml/MatchingEngine.daml, ui/src/components/Exchange/CreateMarket.scss, ui/src/components/Exchange/CreateMarket.tsx, ui/src/components/Exchange/MarketPairs.tsx, ui/src/components/Investor/Investor.scss, ui/src/components/Investor/Investor.tsx, ui/src/components/Investor/InvestorOrders.tsx, ui/src/components/Investor/InvestorTrade.tsx, ui/src/components/Investor/OrderForm.tsx, ui/src/components/common/CardTable.tsx, ui/src/components/common/ExchangeOrderCard.tsx, ui/src/components/common/OrderCard.scss, ui/src/components/common/OrderCard.tsx, ui/src/components/common/RegistryLookup.tsx, ui/src/components/common/TradeCard.tsx
=> Add ccp cleared orders 2

daml.yaml, daml/Demo.daml, ui2/src/claims.ts, ui2/src/pages/registry/NewBinaryOption.tsx
Note there are also changes in contingent-claims submodule, not visible here. (needed to add some operators to `Observation`)
=> Added convertible note and bond to Demo.daml

daml.yaml, daml/Demo.daml, daml/Marketplace/Distribution/Auction/Service.daml, daml/Tests/Distribution/Auction.daml, ui2/package.json, ui2/src/apps/Distribution.tsx, ui2/src/pages/distribution/Assets.tsx, ui2/src/pages/distribution/Auction.tsx
When an auction is only partially allocated, transfer the remaining unallocated asset back to the issuer's trading account
=> Transfer unallocated asset 

ui/src/components/common/Holdings.tsx, ui/src/components/common/RoleSideNav.tsx, ui/src/components/common/TopMenu.tsx, ui/src/websocket/queryStream.ts, ui/src/websocket/websocket.ts
Add a "Loading..." indicator for when the websocket drops, and fix the disconnect issue.
=> Websocket refresh

ui2/src/App.tsx, ui2/src/components/Form/CalendarInput.scss, ui2/src/components/Form/CalendarInput.tsx, ui2/src/index.scss, ui2/src/pages/origination/New.scss, ui2/src/pages/origination/NewBaseInstrument.tsx, ui2/src/pages/origination/NewBinaryOption.scss, ui2/src/pages/origination/NewBinaryOption.tsx, ui2/src/pages/origination/NewConvertibleNote.scss, ui2/src/pages/origination/NewConvertibleNote.tsx
This updates the forms/pages for NewBinaryOption and NewConvertibleNotes
=> New instrument forms

ui2/src/pages/login/QuickSetup.tsx
This was not working before due to `/app` routing issue
=> adding login from quick setup

ui2/src/pages/login/QuickSetup.tsx
Make services a multi select (prerequisite for adding legalName and location fields)
=> Add multiple services

ui2/src/pages/login/QuickSetup.scss, ui2/src/pages/login/QuickSetup.tsx
If the user already has a `VerifiedIdentity` `legalName` and `location` will autofill with the contract data.
=> Adding VerifiedIdentity flow to quick setup modal

triggers/daml/AutoApproval.daml, ui2/src/pages/custody/New.tsx, ui2/src/pages/landing/Landing.tsx, ui2/src/pages/login/QuickSetup.scss, ui2/src/pages/login/QuickSetup.tsx, ui2/src/pages/manage/Manage.scss, ui2/src/pages/network/Clearing.tsx, ui2/src/pages/network/Custody.tsx
- all clearing to quick setup
- add clearing role accept
- add allocation account request
- add account request accept
=> Sales eng quick clear

daml/Marketplace/Clearing/Role.daml, daml/Marketplace/Clearing/Service.daml, daml/Marketplace/Custody/Service.daml, daml/Marketplace/Distribution/Bidding/Service.daml, daml/Marketplace/Distribution/Role.daml, daml/Marketplace/Issuance/Service.daml, daml/Marketplace/Listing/Service.daml, daml/Marketplace/Regulator/Role.daml, daml/Marketplace/Regulator/Service.daml, daml/Marketplace/Settlement/Service.daml, daml/Marketplace/Trading/Matching/Service.daml, daml/Marketplace/Trading/Service.daml, daml/Marketplace/Utils.daml, ui2/src/pages/login/Login.tsx
changes `create Service with ..` for request/offers to use `createOrLookup` to avoid trigger duplicate loops
=> change offer/requests to createOrLookup

daml.yaml, ui2/src/pages/custody/Account.tsx, ui2/src/pages/custody/Assets.tsx, ui2/src/pages/custody/New.tsx, ui2/src/pages/page/TopMenu.scss
Added Allocation accounts to the UI as part of the Wallet screen. Also removed the public party as an observer to newly created accounts in the UI.
=> Add Allocation accounts to the UI

ui2/src/pages/clearing/Member.tsx, ui2/src/pages/clearing/Members.tsx, ui2/src/pages/custody/Account.tsx, ui2/src/pages/distribution/auction/Auction.tsx, ui2/src/pages/issuance/Issuances.tsx, ui2/src/pages/landing/Landing.tsx, ui2/src/pages/origination/Instruments.tsx, ui2/src/util.ts
Some improvements to standardize currency formatting, convert more Ledger Party Ids into readable names, and add the ability to request Bidding services from the Landing page
=> Fix minor bugs

ui2/src/context/OffersContext.tsx, ui2/src/context/RolesContext.tsx, ui2/src/websocket/queryStream.ts
Adds `OffersProvider` and `RolesProvider` to be used in subsequent quick setup PR
=> Role and offer contexts

ui2/src/App.tsx, ui2/src/pages/clearing/Members.tsx, ui2/src/pages/distribution/auction/Auctions.tsx, ui2/src/pages/issuance/Issuances.tsx, ui2/src/pages/listing/Listings.tsx, ui2/src/pages/network/Actions.tsx, ui2/src/pages/network/Clearing.tsx, ui2/src/pages/network/Custody.tsx, ui2/src/pages/network/Distribution.tsx, ui2/src/pages/origination/Instruments.tsx, ui2/src/pages/setup/Offer.tsx
adds action links in the manage page
=> add links in manage pages

README.md, dabl-meta.yaml, daml.yaml, daml/Marketplace/Exchange.daml, daml/Marketplace/Trading.daml, daml/Setup.daml, daml/Setup/Clearing.daml, exberry_adapter/bot/exberry_adapter_bot.py, exberry_adapter/setup.py, triggers/daml.yaml, ui/package.json, ui/src/components/Exchange/MarketPairs.tsx, ui/src/components/Investor/InvestorOrders.tsx
- Make Exberry adapter scan for existing contracts on startup
- Add "Remove Market" to exchange market pairs
- Add Order Request Cancel
=> Exberry pickup

daml/Common.daml, exberry_adapter/bot/exberry_adapter_bot.py
- have exberry adapter scan for contracts on restart
=> add exberry restart

ui/src/pages/QuickSetup/FinishPage.tsx, ui/src/pages/QuickSetup/QuickSetup.tsx
Just use verified IDs given in setup script
=> skip add parties for local quick setup

ui/src/pages/trading/Market.tsx
Small change to remove unnecessary ledger call to split the merged `AssetDeposit` if the merged `Assetdeposit`s quantity matches the trade quantity.
=> Update trading on split deposits

ui/src/App.tsx, ui/src/components/Common/BackButton.tsx, ui/src/pages/custody/Account.tsx, ui/src/pages/custody/New.tsx, ui/src/pages/page/TopMenu.scss, ui/src/pages/page/TopMenu.tsx
=> more granular page labeling

daml/Marketplace/Rule/AllocationAccount.daml, daml/Marketplace/Settlement/Model.daml, docs/user_guide.md, ui/src/context/AutomationContext.tsx, ui/src/pages/QuickSetup/SelectRolesPage.tsx, ui/src/pages/distribution/auction/Auction.tsx, ui/src/pages/setup/SetUp.tsx
- various doc updates
- fix issue where a custody provider being an allocation account nominee would break the settlement rule
- add settlement instruction trigger to exchange startup
- fix automation setup page from infinite looping
- fix link to automation modal
=> fixes and doc updates

ui/src/App.tsx, ui/src/icons/icons.tsx, ui/src/pages/custody/Assets.tsx, ui/src/pages/landing/Landing.tsx, ui/src/pages/page/TopMenu.scss, ui/src/pages/page/TopMenu.tsx, ui/src/paths.ts
Forgot to remove this from sidebar and a few small ui corrections
=> remove setup

dabl-meta.yaml, docs/damlhub_deployment.md, ui/package.json, ui/src/App.tsx
Includes trading fees and misc improvements since rc.1
=> release 0.2.0-rc.2

docs/user_guide.md, ui/src/components/Form/FormErrorHandled.tsx, ui/src/pages/QuickSetup/AddAccountPage.tsx, ui/src/pages/QuickSetup/QuickSetup.scss, ui/src/pages/QuickSetup/RequestServicesPage.tsx, ui/src/pages/QuickSetup/ReviewPage.tsx, ui/src/pages/custody/New.tsx
=> Add account tab

ui/src/pages/QuickSetup/AccountSelection.tsx, ui/src/pages/QuickSetup/RequestServicesPage.tsx
Changes the Quick Setup account selection (with automatic account creation) to be inline fields as a list of required accounts instead of modals
=> switch account selection to be inline on review page

.gitignore, daml/Setup.daml, exberry_adapter/bot/exberry_adapter_bot.py, exberry_adapter/test/daml.yaml, exberry_adapter/test/daml/Tests/Matching.daml, exberry_adapter/test/daml/Utils.daml
fixes the exberry adapter contract sweep to correctly deal with `ExecutionReport`
=> fix adapter

daml.yaml, ui/src/pages/QuickSetup/AssignRolesPage.tsx, ui/src/pages/notifications/Notifications.tsx
little clean up for assigning parties
=> autofill party and remove logs

ui/src/pages/QuickSetup/QuickSetup.scss, ui/src/pages/QuickSetup/QuickSetup.tsx
Show/hide advanced setup options
=> hide advanced setup

daml/Marketplace/Trading.daml, daml/Tests/ExchangeTrade.daml
Fix a bug where if the buyer bid for more than the trade was filled at, the entire collateral would be transferred instead of just the portion owed.
=> 0.1 fix settlement bug

daml.yaml, daml/Demo.daml, daml/Marketplace/Custody/Model.daml, daml/Marketplace/Issuance/AssetDescription.daml, daml/Tests/Utils.daml, triggers/daml.yaml, triggers/test/daml.yaml, ui/daml.yaml, ui/src/components/Claims/util.ts, ui/src/pages/origination/NewBinaryOption.tsx, ui/src/pages/origination/NewConvertibleNote.tsx, ui/src/pages/origination/NewSimpleFuture.tsx
Upgrading the Daml SDK to version 1.17.1 and updating the Contingent Claims library to use the latest version
=> SDK and Contingent Claims upgrade

exberry_adapter/bot/exberry_adapter_bot.py
Change Exberry adapter to not batch commands, which often resulted in one failing command to fail unrelated commands
=> change adapter to not batch

ui/src/components/SetupRequired.tsx
Update info on Setup Required page to reflect latest Hub interface and da-marketplace branches
=> change users to identities, point to correct docs

daml/Marketplace/Lifecycle/Model.daml, daml/Marketplace/Lifecycle/Redemption.daml, daml/Marketplace/Lifecycle/Service.daml, daml/Marketplace/Lifecycle/Snapshot/Model.daml, daml/Marketplace/Lifecycle/Snapshot/Service.daml, daml/Marketplace/Settlement/Hierarchical.daml, daml/SwiftMessage/Message.daml, daml/SwiftMessage/Model/MT564.daml, daml/SwiftMessage/Model/MT566.daml, daml/SwiftMessage/Util.daml, daml/Tests/Distribution/Syndication/IssuerRedemption.daml, daml/Tests/Distribution/Syndication/Lifecycle.daml, daml/Tests/Distribution/Syndication/Origination.daml, daml/Tests/Distribution/Syndication/Setup.daml, daml/Tests/Distribution/Syndication/Util.daml
The PR include changes for 
1. [FL-220](https://digitalasset.atlassian.net/browse/FL-220)
2. [FL-219](https://digitalasset.atlassian.net/browse/FL-219)
3. Refactor to separate snapshot flow from the lifecycling flow
=> Add Flow for MT564 and MT566

daml/Marketplace/Custody/Model.daml, daml/Marketplace/Custody/Service.daml, daml/Tests/Distribution/Syndication/Util.daml
The PR is a small that covers the change in https://digitalasset.atlassian.net/browse/FL-295
=> FL-295: use account owner and provider in account info

daml/Marketplace/Clearing/Market/Service.daml, daml/Marketplace/Clearing/Service.daml, daml/Marketplace/Custody/Service.daml, daml/Marketplace/Lifecycle/Service.daml, daml/Marketplace/Listing/Service.daml, daml/Marketplace/Settlement/Service.daml, daml/Marketplace/Trading/Matching/Service.daml, daml/Marketplace/Trading/Otc/Service.daml, daml/Marketplace/Trading/Service.daml
Corresponding requirement changes described in https://digitalasset.atlassian.net/browse/FL-296?focusedCommentId=109859
=> FL-296: use operator, provider and customer as actors for Terminate when possible

daml/Marketplace/Distribution/Syndication/Bidding/Model.daml, daml/Marketplace/Distribution/Syndication/Structuring/Model.daml, daml/Marketplace/Settlement/Hierarchical.daml, daml/Marketplace/Settlement/Htlc/Delivery.daml, daml/Marketplace/Settlement/Htlc/Instruction.daml, daml/Marketplace/Settlement/Htlc/Trade.daml, daml/Marketplace/Settlement/Htlc/Util.daml, daml/Tests/Distribution/Syndication/Issuance.daml, daml/Tests/Distribution/Syndication/Util.daml
This PR includes below changes
- add HTLC settlement contracts (Instruction, Delivery in HTLC module)
- integrate HTLC settlement contracts with Tranche Template to enable HTLC settlement support in Issuance Flow
- Code refactoring in InstructSettlement choices in Tranche template
=> HTLC creation and integration with issuance flow

daml/Marketplace/Clearing/Market/Service.daml, daml/Marketplace/Clearing/Model.daml, daml/Marketplace/Clearing/Service.daml, daml/Marketplace/Custody/Model.daml, daml/Marketplace/Custody/Service.daml, daml/Marketplace/Distribution/Syndication/Bidding/Model.daml, daml/Marketplace/Distribution/Syndication/Structuring/Model.daml, daml/Marketplace/Lifecycle/Service.daml, daml/Marketplace/Listing/Service.daml, daml/Marketplace/Reporting/Service.daml, daml/Marketplace/Settlement/Hierarchical.daml, daml/Marketplace/Settlement/Htlc/Delivery.daml, daml/Marketplace/Settlement/Htlc/Instruction.daml, daml/Marketplace/Settlement/Htlc/Trade.daml, daml/Marketplace/Settlement/Htlc/Util.daml, daml/Marketplace/Settlement/Service.daml, daml/Marketplace/Trading/Matching/Service.daml, daml/Marketplace/Trading/Otc/Service.daml, daml/Marketplace/Trading/Service.daml, daml/SwiftMessage/Message.daml, daml/SwiftMessage/Model/MT535.daml, daml/SwiftMessage/Model/MT544.daml, daml/SwiftMessage/Model/MT545.daml, daml/SwiftMessage/Model/MT546.daml, daml/SwiftMessage/Model/MT547.daml, daml/SwiftMessage/Model/MT940.daml, daml/SwiftMessage/Util.daml, daml/Tests/Distribution/Syndication/Issuance.daml, daml/Tests/Distribution/Syndication/Lifecycle.daml, daml/Tests/Distribution/Syndication/Util.daml
=> Syndication dev

daml/Marketplace/Issuance/Instrument/Model.daml, daml/Marketplace/Issuance/Instrument/Service.daml, daml/Marketplace/Lifecycle/Model.daml, daml/Marketplace/Reporting/Service.daml, daml/Marketplace/Settlement/Hierarchical/Util.daml, daml/Marketplace/Settlement/Htlc/Util.daml, daml/Tests/Distribution/Syndication/Hedging.daml, daml/Tests/Distribution/Syndication/Lifecycle.daml, daml/Tests/Distribution/Syndication/Origination.daml, daml/Tests/Distribution/Syndication/Util.daml
* FL-358: added unitPar into Bond contract and use it to create Bond claims
* FL-358: update notional in MT535
=> Feature/add par into bond (#497)
